/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClientsService } from "../clients.service";
import { ClientsCreateInput } from "./ClientsCreateInput";
import { Clients } from "./Clients";
import { ClientsFindManyArgs } from "./ClientsFindManyArgs";
import { ClientsWhereUniqueInput } from "./ClientsWhereUniqueInput";
import { ClientsUpdateInput } from "./ClientsUpdateInput";
import { AppointmentsFindManyArgs } from "../../appointments/base/AppointmentsFindManyArgs";
import { Appointments } from "../../appointments/base/Appointments";
import { AppointmentsWhereUniqueInput } from "../../appointments/base/AppointmentsWhereUniqueInput";

export class ClientsControllerBase {
  constructor(protected readonly service: ClientsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Clients })
  async createClients(
    @common.Body() data: ClientsCreateInput
  ): Promise<Clients> {
    return await this.service.createClients({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        interestedIn: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Clients] })
  @ApiNestedQuery(ClientsFindManyArgs)
  async clientsItems(@common.Req() request: Request): Promise<Clients[]> {
    const args = plainToClass(ClientsFindManyArgs, request.query);
    return this.service.clientsItems({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        interestedIn: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Clients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async clients(
    @common.Param() params: ClientsWhereUniqueInput
  ): Promise<Clients | null> {
    const result = await this.service.clients({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        interestedIn: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Clients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClients(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() data: ClientsUpdateInput
  ): Promise<Clients | null> {
    try {
      return await this.service.updateClients({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          interestedIn: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Clients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClients(
    @common.Param() params: ClientsWhereUniqueInput
  ): Promise<Clients | null> {
    try {
      return await this.service.deleteClients({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          interestedIn: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointmentsItems")
  @ApiNestedQuery(AppointmentsFindManyArgs)
  async findAppointmentsItems(
    @common.Req() request: Request,
    @common.Param() params: ClientsWhereUniqueInput
  ): Promise<Appointments[]> {
    const query = plainToClass(AppointmentsFindManyArgs, request.query);
    const results = await this.service.findAppointmentsItems(params.id, {
      ...query,
      select: {
        agent: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateTime: true,
        id: true,
        location: true,
        notes: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointmentsItems")
  async connectAppointmentsItems(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        connect: body,
      },
    };
    await this.service.updateClients({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointmentsItems")
  async updateAppointmentsItems(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        set: body,
      },
    };
    await this.service.updateClients({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointmentsItems")
  async disconnectAppointmentsItems(
    @common.Param() params: ClientsWhereUniqueInput,
    @common.Body() body: AppointmentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointmentsItems: {
        disconnect: body,
      },
    };
    await this.service.updateClients({
      where: params,
      data,
      select: { id: true },
    });
  }
}
