/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PropertiesService } from "../properties.service";
import { PropertiesCreateInput } from "./PropertiesCreateInput";
import { Properties } from "./Properties";
import { PropertiesFindManyArgs } from "./PropertiesFindManyArgs";
import { PropertiesWhereUniqueInput } from "./PropertiesWhereUniqueInput";
import { PropertiesUpdateInput } from "./PropertiesUpdateInput";

export class PropertiesControllerBase {
  constructor(protected readonly service: PropertiesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Properties })
  async createProperties(
    @common.Body() data: PropertiesCreateInput
  ): Promise<Properties> {
    return await this.service.createProperties({
      data: data,
      select: {
        address: true,
        createdAt: true,
        id: true,
        price: true,
        propertyType: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Properties] })
  @ApiNestedQuery(PropertiesFindManyArgs)
  async propertiesItems(@common.Req() request: Request): Promise<Properties[]> {
    const args = plainToClass(PropertiesFindManyArgs, request.query);
    return this.service.propertiesItems({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        price: true,
        propertyType: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Properties })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async properties(
    @common.Param() params: PropertiesWhereUniqueInput
  ): Promise<Properties | null> {
    const result = await this.service.properties({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        price: true,
        propertyType: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Properties })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProperties(
    @common.Param() params: PropertiesWhereUniqueInput,
    @common.Body() data: PropertiesUpdateInput
  ): Promise<Properties | null> {
    try {
      return await this.service.updateProperties({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          id: true,
          price: true,
          propertyType: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Properties })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProperties(
    @common.Param() params: PropertiesWhereUniqueInput
  ): Promise<Properties | null> {
    try {
      return await this.service.deleteProperties({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          price: true,
          propertyType: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
