/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Appointments } from "./Appointments";
import { AppointmentsCountArgs } from "./AppointmentsCountArgs";
import { AppointmentsFindManyArgs } from "./AppointmentsFindManyArgs";
import { AppointmentsFindUniqueArgs } from "./AppointmentsFindUniqueArgs";
import { CreateAppointmentsArgs } from "./CreateAppointmentsArgs";
import { UpdateAppointmentsArgs } from "./UpdateAppointmentsArgs";
import { DeleteAppointmentsArgs } from "./DeleteAppointmentsArgs";
import { AgentsFindManyArgs } from "../../agents/base/AgentsFindManyArgs";
import { Agents } from "../../agents/base/Agents";
import { Clients } from "../../clients/base/Clients";
import { AppointmentsService } from "../appointments.service";
@graphql.Resolver(() => Appointments)
export class AppointmentsResolverBase {
  constructor(protected readonly service: AppointmentsService) {}

  async _appointmentsItemsMeta(
    @graphql.Args() args: AppointmentsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Appointments])
  async appointmentsItems(
    @graphql.Args() args: AppointmentsFindManyArgs
  ): Promise<Appointments[]> {
    return this.service.appointmentsItems(args);
  }

  @graphql.Query(() => Appointments, { nullable: true })
  async appointments(
    @graphql.Args() args: AppointmentsFindUniqueArgs
  ): Promise<Appointments | null> {
    const result = await this.service.appointments(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Appointments)
  async createAppointments(
    @graphql.Args() args: CreateAppointmentsArgs
  ): Promise<Appointments> {
    return await this.service.createAppointments({
      ...args,
      data: {
        ...args.data,

        agent: args.data.agent
          ? {
              connect: args.data.agent,
            }
          : undefined,

        client: args.data.client
          ? {
              connect: args.data.client,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Appointments)
  async updateAppointments(
    @graphql.Args() args: UpdateAppointmentsArgs
  ): Promise<Appointments | null> {
    try {
      return await this.service.updateAppointments({
        ...args,
        data: {
          ...args.data,

          agent: args.data.agent
            ? {
                connect: args.data.agent,
              }
            : undefined,

          client: args.data.client
            ? {
                connect: args.data.client,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Appointments)
  async deleteAppointments(
    @graphql.Args() args: DeleteAppointmentsArgs
  ): Promise<Appointments | null> {
    try {
      return await this.service.deleteAppointments(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Agents], { name: "agentsItems" })
  async findAgentsItems(
    @graphql.Parent() parent: Appointments,
    @graphql.Args() args: AgentsFindManyArgs
  ): Promise<Agents[]> {
    const results = await this.service.findAgentsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Agents, {
    nullable: true,
    name: "agent",
  })
  async getAgent(
    @graphql.Parent() parent: Appointments
  ): Promise<Agents | null> {
    const result = await this.service.getAgent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Clients, {
    nullable: true,
    name: "client",
  })
  async getClient(
    @graphql.Parent() parent: Appointments
  ): Promise<Clients | null> {
    const result = await this.service.getClient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
