/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AgentsWhereUniqueInput } from "../../agents/base/AgentsWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AgentsListRelationFilter } from "../../agents/base/AgentsListRelationFilter";
import { ClientsWhereUniqueInput } from "../../clients/base/ClientsWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class AppointmentsWhereInput {
  @ApiProperty({
    required: false,
    type: () => AgentsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AgentsWhereUniqueInput)
  @IsOptional()
  @Field(() => AgentsWhereUniqueInput, {
    nullable: true,
  })
  agent?: AgentsWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AgentsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AgentsListRelationFilter)
  @IsOptional()
  @Field(() => AgentsListRelationFilter, {
    nullable: true,
  })
  agentsItems?: AgentsListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ClientsWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientsWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientsWhereUniqueInput, {
    nullable: true,
  })
  client?: ClientsWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  dateTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  location?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  notes?: StringNullableFilter;
}

export { AppointmentsWhereInput as AppointmentsWhereInput };
